/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#f837e0",
        "on-primary-container": "#520049",
        "primary": "#fface9",
        "on-primary": "#5d0054",
        "primary-fixed": "#ffd7f1",
        "primary-fixed-dim": "#fface9",
        "on-primary-fixed": "#3a0033",
        "on-primary-fixed-variant": "#840077",
        "secondary": "#ffb59b",
        "secondary-container": "#7e2b07",
        "on-secondary": "#5b1a00",
        "on-secondary-container": "#ff9b77",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#ffb59b",
        "on-secondary-fixed": "#380d00",
        "on-secondary-fixed-variant": "#7e2b07",
        "tertiary": "#e9b6e7",
        "tertiary-container": "#b082af",
        "on-tertiary": "#47224a",
        "on-tertiary-container": "#3f1c42",
        "tertiary-fixed": "#ffd6fc",
        "tertiary-fixed-dim": "#e9b6e7",
        "on-tertiary-fixed": "#2f0c33",
        "on-tertiary-fixed-variant": "#603961",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-surface-variant": "#dcbed0",
        "outline": "#a4899a",
        "outline-variant": "#56404f",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#ad009c",
        "surface-tint": "#fface9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-sm": ["Hanken Grotesk"],
      "display-lg": ["Libre Caslon Text"],
      "body-md": ["Hanken Grotesk"],
      "body-lg": ["Hanken Grotesk"],
      "headline-lg": ["Libre Caslon Text"],
      "headline-lg-mobile": ["Libre Caslon Text"],
      "headline-md": ["Libre Caslon Text"],
        },

      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
};
